import random
triggers = ['.roa','rule of acquisition', 'rules of acquisition','ferengi']
options = ['Once you have their money ... never give it back.',
'Never pay more for an acquisition than you have to.',
'Never allow family to stand in the way of opportunity.',
'A man is only worth the sum of his possessions.',
'Keep your ears open.',
'Small print leads to large risk.',
'Opportunity plus instinct equals profit.',
'Greed is eternal.',
'Anything worth doing is worth doing for money.',
'A deal is a deal ... until a better one comes along.',
'A contract is a contract is a contract (but only between Ferengi).',
'A Ferengi without profit is no Ferengi at all.',
'Satisfaction is not guaranteed.',
'Never place friendship above profit.',
'A wise man can hear profit in the wind.',
'Nothing is more important than your health--except for your money.',
'There\'s nothing more dangerous than an honest businessman.',
'Never make fun of a Ferengi\'s mother ... insult something he cares about instead.',
'It never hurts to suck up to the boss.',
'War is good for business.',
'Peace is good for business.',
'She can touch your lobes but never your latinum.',
'Profit is its own reward.',
'Never confuse wisdom with luck.',
'Expand, or die.',
'Don\'t trust a man wearing a better suit than your own.',
'The bigger the smile, the sharper the knife.',
'Females and finance don\'t mix.',
'Never ask when you can take.',
'Good customers are as rare as latinum -- treasure them.',
'There is no substitute for success.',
'Free advice is seldom cheap.',
'Keep your lies consistent.',
'The riskier the road, the greater the profit.',
'Win or lose, there\'s always Hyperian beetle snuff.',
'Home is where the heart is ... but the stars are made of latinum.',
'Every once in a while, declare peace. It confuses the hell out of your enemies.',
'Beware of the Vulcan greed for knowledge.',
'The flimsier the product, the higher the price.',
'Never let the competition know what you\'re thinking.',
'Ask not what your profits can do for you, but what you can do for your profits.',
'Females and finances don\'t mix.',
'Enough ... is never enough.',
'Every man has his price.',
'Trust is the biggest liability of all.',
'Nature decays, but latinum lasts forever.',
'Sleep can interfere with profit.',
'Faith moves mountains ... of inventory.',
'There is no honour in poverty.',
'Dignity and an empty sack is worth the sack.',
'Treat people in your debt like family ... exploit them.',
'Never have sex with the boss\'s sister.',
'Always have sex with the boss.',
'You can\'t free a fish from water.',
'Everything is for sale, even friendship.',
'Even a blind man can recognize the glow of latinum.',
'You can\'t make a deal if you\'re dead.',
'Wives serve, brothers inherit.',
'Only fools pay retail.',
'There\'s nothing wrong with charity ... as long as it winds up in your pocket.',
'Even in the worst of times someone turns a profit.',
'Whisper your way to success.',
'Know your enemies ... but do business with them always.',
'Not even dishonesty can tarnish the shine of profit.',
'Let others keep their reputation. You keep their money.',
'Hear all, trust nothing.',
'Never cheat a Klingon ... unless you\'re sure you can get away with it.',
'It\'s always good business to know about new customers before they walk in the door.',
'The justification for profit is profit.',
'New customers are like razortoothed grubworms. They can be succulent, but sometimes they can bite back.',
'Sometimes the only thing more dangerous than a question is an answer.',
'Employees are rungs on the ladder of success. Don\'t hesitate to step on them.',
'Never begin a negotiation on an empty stomach.',
'You can\'t free a fish from water.',
'Always know what you\'re buying.',
'Beware the man who doesn\'t make time for oo-mox.',
'Latinum lasts longer than lust.',
'You can\'t buy fate.',
'Never be afraid to mislabel a product.',
'More is good ... all is better.',
'A wife is a luxury ... a smart accountant is a necessity.',
'A wealthy man can afford anything except a conscience.',
'Never allow doubt to tarnish your love of latinum.',
'When in doubt, lie.',
'Deep down everyone\'s a Ferengi.',
'No good deed ever goes unpunished.']
def handle(f,sender,msg,loc,rsvp,send):
	for trigger in triggers:
		if trigger in msg:
			rsvp(f,loc,random.choice(options))
			return
def privhandle(f,sender,msg,loc,rsvp,send):
	handle(f,sender,msg,loc,rsvp,send)